services:
  # FastAPI web service
  - type: web
    name: grammar-heroes-api
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    startCommand: >
      gunicorn -k uvicorn.workers.UvicornWorker -w 2
      -b 0.0.0.0:$PORT app.main:app
    preDeployCommand: alembic upgrade head
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_SYNC
        sync: false
      - key: REDIS_URL
        value: redis://redis:6379
      - key: DEBUG
        value: "false"
      - key: SAPLING_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        value: /etc/secrets/firebase_sa.json
    secretFiles:
      - name: firebase_sa.json

  # Redis as worker service
  - type: worker
    name: redis
    env: docker
    image: redis:7-alpine
    autoDeploy: false
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1