"""Session management implemented

Revision ID: 626018a99f10
Revises: fab687ff9a3a
Create Date: 2025-11-07 13:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision id for this new script
revision: str = '626018a99f10'

# id of the migration this script is "on top of"
# This is the ID from the file we created last time.
down_revision: str | None = 'fab687ff9a3a' 

branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - manually created ###
    
    # 1. Add the new column, nullable=True as per your model
    op.add_column(
        'users', 
        sa.Column('active_session_auth_time', sa.BigInteger(), nullable=True)
    )
    
    # 2. Create the index on that new column
    op.create_index(
        op.f('ix_users_active_session_auth_time'), 
        'users', 
        ['active_session_auth_time'], 
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - manually created ###
    
    # 1. Drop the index
    op.drop_index(
        op.f('ix_users_active_session_auth_time'), 
        table_name='users'
    )
    
    # 2. Drop the column
    op.drop_column('users', 'active_session_auth_time')
    # ### end Alembic commands ###